### PR TITLE
Update library.properties

### PR DESCRIPTION
**Pull request by s-celles**

### CODE REVIEW

**Comment by olikraus** [comment]
license field is not supported: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#library-metadata

In the best case it will be ignored by the Arduino IDE, in the worst case, U8g2 will break the IDE.
So why shell I add this?

**Comment by s-celles** [comment]
It's supported, but not well documented
See https://github.com/arduino/Arduino/issues/6646

**Comment by olikraus** [comment]
Actually it took me some time to read though arduino/Arduino#6646, but I did not found any hint that the `license` field is already implemented. arduino/Arduino#6646 is still open. From where exactly do you see/derive that the field is valid?

**Comment by s-celles** [comment]
This is probably a bad answer... but major libraries such as https://www.arduinolibraries.info/libraries/arduino-json are using this field

**Pull request merged**
