### PR TITLE
add wqy_bitmap font

### PR DESCRIPTION
**Pull request by gdbdzgd**
easy show chinese ut8f fonts

code from git@github.com:larryli/u8g2_wqy.git

Signed-off-by: Zhang, Guodong <gdzhang@linx-info.com>

	modify：     u8g2.h
	modify：     u8g2_fonts.c

### CODE REVIEW

**Comment by olikraus** [comment]
Unfortunately the integration works differently. u8g2_fonts.c is generated automatically. Any patches will be overwritten with the next font generation run. Can you send me the bdf files and the bdfconv options for their generation?

**Comment by gdbdzgd** [comment]
@olikraus  i got the code from https://github.com/larryli/u8g2_wqy
and tested with esp32-nodemcu firmware show chinese fonts with lua code 

bdf files in https://github.com/larryli/u8g2_wqy/tree/master/bdf

bdfconv options in https://github.com/larryli/u8g2_wqy/blob/master/build.sh
```
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/chinese1.map -n u8g2_font_wqy12_t_chinese1 -o _u8g2_font_wqy12_t_chinese1.c
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/chinese2.map -n u8g2_font_wqy12_t_chinese2 -o _u8g2_font_wqy12_t_chinese2.c
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/chinese3.map -n u8g2_font_wqy12_t_chinese3 -o _u8g2_font_wqy12_t_chinese3.c
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/gb2312.map -n u8g2_font_wqy12_t_gb2312 -o _u8g2_font_wqy12_t_gb2312.c
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/gb2312a.map -n u8g2_font_wqy12_t_gb2312a -o _u8g2_font_wqy12_t_gb2312a.c
./bdfconv bdf/wenquanyi_9pt.bdf -b 0 -f 1 -M maps/gb2312b.map -n u8g2_font_wqy12_t_gb2312b -o _u8g2_font_wqy12_t_gb2312b.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/chinese1.map -n u8g2_font_wqy13_t_chinese1 -o _u8g2_font_wqy13_t_chinese1.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/chinese2.map -n u8g2_font_wqy13_t_chinese2 -o _u8g2_font_wqy13_t_chinese2.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/chinese3.map -n u8g2_font_wqy13_t_chinese3 -o _u8g2_font_wqy13_t_chinese3.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/gb2312.map -n u8g2_font_wqy13_t_gb2312 -o _u8g2_font_wqy13_t_gb2312.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/gb2312a.map -n u8g2_font_wqy13_t_gb2312a -o _u8g2_font_wqy13_t_gb2312a.c
./bdfconv bdf/wenquanyi_10pt.bdf -b 0 -f 1 -M maps/gb2312b.map -n u8g2_font_wqy13_t_gb2312b -o _u8g2_font_wqy13_t_gb2312b.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/chinese1.map -n u8g2_font_wqy14_t_chinese1 -o _u8g2_font_wqy14_t_chinese1.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/chinese2.map -n u8g2_font_wqy14_t_chinese2 -o _u8g2_font_wqy14_t_chinese2.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/chinese3.map -n u8g2_font_wqy14_t_chinese3 -o _u8g2_font_wqy14_t_chinese3.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/gb2312.map -n u8g2_font_wqy14_t_gb2312 -o _u8g2_font_wqy14_t_gb2312.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/gb2312a.map -n u8g2_font_wqy14_t_gb2312a -o _u8g2_font_wqy14_t_gb2312a.c
./bdfconv bdf/wenquanyi_13px.bdf -b 0 -f 1 -M maps/gb2312b.map -n u8g2_font_wqy14_t_gb2312b -o _u8g2_font_wqy14_t_gb2312b.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/chinese1.map -n u8g2_font_wqy15_t_chinese1 -o _u8g2_font_wqy15_t_chinese1.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/chinese2.map -n u8g2_font_wqy15_t_chinese2 -o _u8g2_font_wqy15_t_chinese2.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/chinese3.map -n u8g2_font_wqy15_t_chinese3 -o _u8g2_font_wqy15_t_chinese3.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/gb2312.map -n u8g2_font_wqy15_t_gb2312 -o _u8g2_font_wqy15_t_gb2312.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/gb2312a.map -n u8g2_font_wqy15_t_gb2312a -o _u8g2_font_wqy15_t_gb2312a.c
./bdfconv bdf/wenquanyi_11pt.bdf -b 0 -f 1 -M maps/gb2312b.map -n u8g2_font_wqy15_t_gb2312b -o _u8g2_font_wqy15_t_gb2312b.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/chinese1.map -n u8g2_font_wqy16_t_chinese1 -o _u8g2_font_wqy16_t_chinese1.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/chinese2.map -n u8g2_font_wqy16_t_chinese2 -o _u8g2_font_wqy16_t_chinese2.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/chinese3.map -n u8g2_font_wqy16_t_chinese3 -o _u8g2_font_wqy16_t_chinese3.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/gb2312.map -n u8g2_font_wqy16_t_gb2312 -o _u8g2_font_wqy16_t_gb2312.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/gb2312a.map -n u8g2_font_wqy16_t_gb2312a -o _u8g2_font_wqy16_t_gb2312a.c
./bdfconv bdf/wenquanyi_12pt.bdf -b 0 -f 1 -M maps/gb2312b.map -n u8g2_font_wqy16_t_gb2312b -o _u8g2_font_wqy16_t_gb2312b.c
cat header.txt _*.c > src/u8g2_font_wqy.c
```

**Comment by olikraus** [comment]
this will be handled as an issue: https://github.com/olikraus/u8g2/issues/455

**Comment by gdbdzgd** [comment]
expecting

**Pull request closed without merging**
