### PR TITLE
added st7565 based Powertip PE12864_004

### PR DESCRIPTION
**Pull request by morlac**
based on the ST7565_EA_DOGM128 I added the Powertip PE12864_004 display
it has just a little x-offset (4px) ..
http://eshop-bg.com/PDFs/LCD/PE12864LRU-004-H.pdf

### CODE REVIEW

**Comment by olikraus** [comment]
Unfortunately, this is the wrong project. Correct project is "olikraus/u8g2"
The other point is this: Are you sure, that there is no other ST7565 constructor, which fits to your project?

**Comment by olikraus** [comment]
Maybe we should proceed like this: 
Please create an issue in u8g2 project, append the modified code to the issue, I will then add this to project.

**Comment by morlac** [comment]
I tested all of them .. either nothing visible at all or completely dark or shifted by 64 pixel in y-direction.
The displays I want to control are salvaged from old Hypercom POS-terminals which I can get some hundrets of before destruction for my local Makerspace - planing to produce badges for the CCC-Congres :)

I found the best match to be the ST7565_EA_DOGM128 constructor but with a default x-offset of 4 - so I simply created a new Class [..] with the common display-info plus the default x-offset of 4.

I surely can create an issue in u8g2 project with the added code ..

**Comment by olikraus** [comment]
Yes, please add the issue to u8g2 project.

**Comment by olikraus** [comment]
Code of this repo will be overwritten by the "u8g2" master project. So "merge" does not make sense here. I would be happy to receive the pull request for u8g2.

**Comment by olikraus** [comment]
as mentioned: pull request must go to u8g2 project

**Pull request closed without merging**
