### PR TITLE
Could you please add this model to the library?

### PR DESCRIPTION
**Pull request by Tiky169**
Hi,olikraus,
      I wrote programs for two models based on the latest u8g2 library.  One is a 1.12 inch OLED: OEL1M0201;   the other is a 0.78 inch OLED: TK078F288. 
      5 files need to be modified to be usable. They are:  U8g2lib.h , u8g2.h , u8g2_d_setup.c , u8x8_d_sh1107.c , u8x8.h
      Apply this module in the same way as your original example.
      such as:
      U8G2_SH1107_TK078F288_80X128_F_4W_HW_SPI  u8g2(U8G2_R0, /* CS=*/ D8, /* DC=*/ D3, /* reset=*/ U8X8_PIN_NONE);
      U8G2_SH1107_HJR_OEL1M0201_96X96_F_SW_I2C u8g2(U8G2_R0, /* SCL=*/ D4, /* SDA=*/ D3, /* reset=*/ U8X8_PIN_NONE);
      Looking forward to your reply, thanks!

### CODE REVIEW

**Comment by olikraus** [comment]
I need the pull request to u8g2 project instead.
Thanks

**Comment by olikraus** [comment]
Maybe create an issue at u8g2 project and add the updated sh1107 code. I will then update the lib.

**Comment by Tiky169** [comment]
I am sorry,  this code for two models based on U8g2_Arduino, not u8g2 library. I accidentally wrote the wrong thing in the front and created a misunderstanding.

**Comment by olikraus** [comment]
U8g2_Arduino is a read only copy of u8g2 lib. Pull requeste for U8g2_Arduino do not make sense, because they will be overwritten by u8g2

Not an issue, just create an issue at u8g2

**Comment by Tiky169** [comment]
Thank you! I understand.

**Pull request closed without merging**
